/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-26 16:56:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.METAORDER.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.dto.*;
import meta.mail.*;
import meta.vo.*;
import meta.util.*;
import meta.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/METAORDER/main/main_include/footer.jsp", Long.valueOf(1653584174031L));
    _jspx_dependants.put("/METAORDER/main/main_include/header.jsp", Long.valueOf(1653584174054L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("meta.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("meta.mail");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");

accountVO user = (accountVO)session.getAttribute("login");

SearchVO searchVO = new SearchVO(request);
ListDTO  listDTO  = new ListDTO(searchVO);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("	<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("		<title>메타벅스</title>\r\n");
      out.write("		<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/all.css\">\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>");
      out.write("\r\n");
      out.write("		<table align=center width=500px>\r\n");
      out.write("			<tr style=\"height:100px;\">\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<h2 class=\"title\">\r\n");
      out.write("						안녕하세요.\r\n");
      out.write("						<br>\r\n");
      out.write("						메타벅스입니다.\r\n");
      out.write("					</h2>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"height:200px; \">\r\n");
      out.write("				<td colspan=\"4\" style=\"box-shadow: 5px 5px 5px 5px gray;\">\r\n");
      out.write("					");

					if( user == null )
					{
						
      out.write("\r\n");
      out.write("						메타벅스 리워드<br>\r\n");
      out.write("						회원 신규 가입 첫 구매시,<br>\r\n");
      out.write("						무료음료 혜택을 드려요!<br>\r\n");
      out.write("						<br>\r\n");
      out.write("						<br><a class=\"btn\" href=\"login.jsp\">로그인</a>");

					}else
					{
						
      out.write("\r\n");
      out.write("						카드 등록 후 <br>\r\n");
      out.write("						다양한 혜택을 누려보세요!<br>\r\n");
      out.write("						<br>\r\n");
      out.write("						<br><a class=\"btn\" href=\"../pay/index.jsp\">카드등록</a>");

					}
					
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"height:50px;\">\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<a href=\"../board/noticelist.jsp\">What's New</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

			int total = listDTO.GetTotal();
			BoardDTO boardDTO	= new BoardDTO();

			listDTO.GetList(searchVO.getCurpage());

			int size = listDTO.GetListTotal();
			int seqno = total - (searchVO.getCurpage() - 1) * 10;
			for(int i=0; i < 3; i++)
			{
				boardVO vo = listDTO.GetItem(i);
				boardVO voForImg  = boardDTO.Read(vo.getBoard_no(), false);
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=center colspan=\"4\" style=\"box-shadow: 5px 5px 5px 5px gray; \">\r\n");
      out.write("						");

						if(voForImg.getAttachs().size() != 0 )
						{
							attachVO attach = voForImg.getAttachs().get(0);
							
      out.write("\r\n");
      out.write("							<div style=\"width:500px; height:300px; overflow: hidden;\">\r\n");
      out.write("							<a href=\"../board/event.jsp?");
      out.print( searchVO.GetViewLink(vo.getBoard_no(), vo.getBoard_kind()) );
      out.write("\">\r\n");
      out.write("								<img src=\"../board/download.jsp?file=");
      out.print( attach.getAtt_pname() );
      out.write("&name=");
      out.print( attach.getAtt_lname() );
      out.write("\" width=\"500px\" height=auto>\r\n");
      out.write("							</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

						}
							
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

			}
			
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<tr style=\"position: fixed;\r\n");
      out.write("						background-color: white; /*임의색상*/\r\n");
      out.write("						bottom: 0;\r\n");
      out.write("						height: 6rem;\">\r\n");
      out.write("				<td width=125px align=center>\r\n");
      out.write("					<a href=\"../main/index.jsp\"><img src=\"../img/homesel.png\"><div>Home</div></a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=125px align=center>\r\n");
      out.write("					<a href=\"../pay/index.jsp\"><img src=\"../img/pay.png\"><div>Pay</div></a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=125px align=center>\r\n");
      out.write("					<a href=\"../order/index.jsp\"><img src=\"../img/order.png\"><div>Order</div></a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=125px align=center>\r\n");
      out.write("					<a href=\"../other/index.jsp\"><img src=\"../img/other.png\"><div>Other</div></a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
