/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-27 05:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.METAORDER.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.dto.*;
import meta.mail.*;
import meta.vo.*;
import meta.util.*;
import meta.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/METAORDER/main/main_include/header.jsp", Long.valueOf(1653584174054L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("meta.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("meta.mail");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");

accountVO user = (accountVO)session.getAttribute("login");

SearchVO searchVO = new SearchVO(request);
ListDTO  listDTO  = new ListDTO(searchVO);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("	<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("		<title>메타벅스</title>\r\n");
      out.write("		<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/all.css\">\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		window.onload = function()\r\n");
      out.write("		{\r\n");
      out.write("			document.login.userid.focus()\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function Loginbutton()\r\n");
      out.write("		{\r\n");
      out.write("			if($(\"#userid\").val() == \"\")\r\n");
      out.write("			{\r\n");
      out.write("				alert(\"아이디를 입력하세요.\");\r\n");
      out.write("				$(\"#userid\").focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}		\r\n");
      out.write("			if($(\"#userpw\").val() == \"\")\r\n");
      out.write("			{\r\n");
      out.write("				alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("				$(\"#userpw\").focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			//document.login.submit();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				url: \"loginok.jsp\",\r\n");
      out.write("				dataType: \"html\",\r\n");
      out.write("				data: \r\n");
      out.write("				{\r\n");
      out.write("			        id: $(\"#userid\").val(),\r\n");
      out.write("			        pw: $(\"#userpw\").val()\r\n");
      out.write("			    },	\r\n");
      out.write("				success : function(data) \r\n");
      out.write("				{\r\n");
      out.write("					data = data.trim();\r\n");
      out.write("					if(data == \"OK\")\r\n");
      out.write("					{\r\n");
      out.write("						//로그인 완료됨\r\n");
      out.write("						document.location = \"../main/index.jsp\";\r\n");
      out.write("					}else\r\n");
      out.write("					{\r\n");
      out.write("						alert(\"아이디 혹은 비밀번호가 맞지 않습니다.\")\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			return false;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("		<table align=center width=500px>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<a href=\"index.jsp\"><img src=\"../img/back.png\"></a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"height:100px;\">\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<h2>\r\n");
      out.write("						로그인\r\n");
      out.write("					</h2>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div><img src=\"../img/CoffeeLogo.png\"></div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"height:200px;\">\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<h2>\r\n");
      out.write("						안녕하세요.<br>\r\n");
      out.write("						메타벅스입니다.\r\n");
      out.write("					</h2>\r\n");
      out.write("					<h4>회원 서비스 이용을 위해 로그인 해주세요.</h4>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=center>\r\n");
      out.write("					<form name=\"login\" method=\"post\" action=\"loginok.jsp\">\r\n");
      out.write("						<div><input type=\"text\" style=\"width:20rem; height:3rem; font-size:3rem;\" id=\"userid\" name=\"userid\" placeholder=\"아이디\" value=\"meta\"></div>\r\n");
      out.write("						<br>\r\n");
      out.write("						<div><input type=\"password\" style=\"width:20rem; height:3rem; font-size:3rem;\" id=\"userpw\" name=\"userpw\" placeholder=\"비밀번호\" value=\"1231\"></div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=center>\r\n");
      out.write("					<a href=\"searchid.jsp\">아이디찾기</a> | <a href=\"searchpw.jsp\">비밀번호찾기</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"4\" style=\"border-top:10px; height:1px;background-color:#A6A6A6\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" align=center height=100px; >\r\n");
      out.write("					<div><a class=\"btn\" href=\"javascript:Loginbutton();\">로그인하기</a></div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
