/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-27 05:09:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HOME;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.dto.*;
import meta.vo.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/HOME/include/tail.jsp", Long.valueOf(1653310125863L));
    _jspx_dependants.put("/HOME/include/head.jsp", Long.valueOf(1653628156133L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String userid ="";
//accountVO loginVO = (accountVO)session.getAttribute("login");
accountVO loginVO  = (accountVO) session.getAttribute("accountVO");





if(loginVO !=null)
{
 userid = loginVO.id();
}

      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <title>MetaBucks</title>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=1180\">\r\n");
      out.write("	<meta name=\"Author\" content=\"MetaBucks\">\r\n");
      out.write("	<meta name=\"description\" content=\"메타벅스\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//fonts.googleapis.com/earlyaccess/notosanskr.css\" />\r\n");
      out.write("	<link type=\"text/css\" rel=\"stylesheet\" href=\"css/@default.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/slick.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n");
      out.write("	<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write("	\r\n");
      out.write(" <!--Wrap-->\r\n");
      out.write(" <div id=\"wrap\" class=\"\">\r\n");
      out.write("	<!--Header-->\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"h_inner\" style=\"padding-bottom: 0px;\">\r\n");
      out.write("			<span class=\"gnb_bg\"></span>\r\n");
      out.write("			<div class=\"join\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"login/login.jsp\">\r\n");
      out.write("					");

						if(loginVO == null)
						{
							
      out.write("\r\n");
      out.write("								Sign In\r\n");
      out.write("							");

						}else
						{
							
      out.write("\r\n");
      out.write("							( ");
      out.print(userid  );
      out.write(" )님 환영합니다\r\n");
      out.write("							<a href=\"login/logout.jsp\" class=\"btnlogout\">로그아웃</a>\r\n");
      out.write("							");

						}
      out.write("\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<h1 id=\"logo\"><a href=\"index.jsp\"><span></span>메타벅스</a></h1>\r\n");
      out.write("			<div class=\"gnb_wrap\" id=\"gnb_wrap\">\r\n");
      out.write("				<ul class=\"gnb\">\r\n");
      out.write("					<li><a href=\"nav/about1.jsp\">About us</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"nav/about1.jsp\">Brand</a></li>\r\n");
      out.write("							<li><a href=\"nav/about2.jsp\">Coffee</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"nav/menu.jsp\">MENU</a></li>\r\n");
      out.write("					<li><a href=\"nav/store.jsp\">SHOP</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"nav/store.jsp\">매장위치안내</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"nav/contact.jsp\">Contact</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"board/bindex.jsp\">공지사항</a></li>\r\n");
      out.write("							<li><a href=\"nav/contact.jsp\">이메일 문의하기</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					");
 
					if(loginVO != null)
					{
						
      out.write("\r\n");
      out.write("						<li><a href=\"mypage/userinfo.jsp\">Members</a>\r\n");
      out.write("							<ul class=\"gsnb\">\r\n");
      out.write("								<li><a href=\"mypage/userinfo.jsp\">My Page</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("						\r\n");
      out.write("						<script>\r\n");
      out.write("						//alert(\" 로그인 해주세요\");\r\n");
      out.write("						</script>\r\n");
      out.write("						");

					}
					
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div><!--END Header-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!--Container-->\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Visual -->\r\n");
      out.write("		<div class=\"mv_wrap\">\r\n");
      out.write("			<div class=\"mv\">\r\n");
      out.write("			<div class=\"itema\" style=\"background-image:url('image/wall.jpg');\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div><!-- END Visual -->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Outer -->\r\n");
      out.write("		<div class=\"mv\">\r\n");
      out.write("			<h2 class=\"m_tit\">CREATING A NEW CULTURE</h2>\r\n");
      out.write("			<div class=\"m_mid\">\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<p class=\"stit\">세상에 없었던 카페</p>\r\n");
      out.write("					<span class=\"vline\"></span>\r\n");
      out.write("					<p class=\"desc\">프랑스의 최고급 커피 메오와 이태리 페레날레 두 개의 커피빈을 수입하여 기존의 벤딩머신과는 차원이 다른 커피의 맛을 느낄 수 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<p class=\"stit\">무인시스템 운영</p>\r\n");
      out.write("					<span class=\"vline\"></span>\r\n");
      out.write("					<p class=\"desc\">터치카페는 100% 무인시스템으로 운영됩니다.<br>세콤으로 cctv 및 보안시스템을 갖추었고, 전기 전원은 사용자에 맞게 시간을 설정하여 자동으로 운영할 수 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<p class=\"stit\">위생적인 카페</p>\r\n");
      out.write("					<span class=\"vline\"></span>\r\n");
      out.write("					<p class=\"desc\">커피벤딩머신샵의 가장 취약점으로 알려진 위생 부분은 걱정하실 필요가 전혀 없습니다.<br>터치카페는 세스코에 가입하여 꼼꼼히 관리되고 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	jQuery(document).ready(function($){\r\n");
      out.write("		$(\".b_customer\").slick({\r\n");
      out.write("			arrows:false,\r\n");
      out.write("			dots:true,\r\n");
      out.write("			autoplay:true\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>			\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"outer brand_cus\">\r\n");
      out.write("				<h3 class=\"sec_tit\">Customer</h3>\r\n");
      out.write("				<p class=\"sec_desc\">지금 소비자들이 원하는 ‘새로운 트렌드’</p>\r\n");
      out.write("				<ul class=\"b_customer\">\r\n");
      out.write("					<li><img src=\"image/coffee_meo.jpg\" alt=\"\">\r\n");
      out.write("						<em>21.5인치 Full HD<br>터치 스크린의 편의성</em>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><img src=\"image/coffee_perlanera.jpg\" alt=\"\">\r\n");
      out.write("						<em>합리적 가격으로 즐기는<br>최상의 커피 맛</em>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><img src=\"image/coffee_regilait.jpg\" alt=\"\">\r\n");
      out.write("						<em>간편한<br>카드 결제 시스템</em>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!-- END Outer -->\r\n");
      out.write("	</div><!--END Container-->\r\n");
      out.write("  <!-- 우측 문의 퀵배너 -->\r\n");
      out.write("\r\n");
      out.write("	<form name=\"quick_online\" method=\"post\" action=\"quick/quick_onlineok.jsp\">\r\n");
      out.write("		<div class=\"quickBox\">\r\n");
      out.write("			<p class=\"quick_name\">창업상담</p>\r\n");
      out.write("			<p class=\"quick_tell\">1588-1234</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"quick_info\">\r\n");
      out.write("				<input type=\"text\" placeholder=\"성함\" name=\"name\">\r\n");
      out.write("				<input type=\"text\" placeholder=\"연락처\" name=\"data1\" onkeyup=\"this.value=this.value.replace(/[^0-9]/g,'')\" maxlength='11'>\r\n");
      out.write("				<input type=\"text\" placeholder=\"이메일\" name=\"email\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- \r\n");
      out.write("			<div class=\"quick_selectBox\">\r\n");
      out.write("				<select name=\"sido\" id=\"\" onchange=\"call_gugn(this.value)\">\r\n");
      out.write("					<option value=\"\">도/시</option>\r\n");
      out.write("											<option value=\"강원도\">강원도</option>\r\n");
      out.write("												<option value=\"경기도\">경기도</option>\r\n");
      out.write("												<option value=\"경상남도\">경상남도</option>\r\n");
      out.write("												<option value=\"경상북도\">경상북도</option>\r\n");
      out.write("												<option value=\"광주광역시\">광주광역시</option>\r\n");
      out.write("												<option value=\"대구광역시\">대구광역시</option>\r\n");
      out.write("												<option value=\"대전광역시\">대전광역시</option>\r\n");
      out.write("												<option value=\"부산광역시\">부산광역시</option>\r\n");
      out.write("												<option value=\"서울특별시\">서울특별시</option>\r\n");
      out.write("												<option value=\"세종특별자치시\">세종특별자치시</option>\r\n");
      out.write("												<option value=\"울산광역시\">울산광역시</option>\r\n");
      out.write("												<option value=\"인천광역시\">인천광역시</option>\r\n");
      out.write("												<option value=\"전라남도\">전라남도</option>\r\n");
      out.write("												<option value=\"전라북도\">전라북도</option>\r\n");
      out.write("												<option value=\"제주특별자치도\">제주특별자치도</option>\r\n");
      out.write("												<option value=\"충청남도\">충청남도</option>\r\n");
      out.write("												<option value=\"충청북도\">충청북도</option>\r\n");
      out.write("										</select>\r\n");
      out.write("				<select name=\"gugun\" id=\"gugun\">\r\n");
      out.write("					<option value=\"\">구/군</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div> -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"quick_check\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"check\">\r\n");
      out.write("				<label for=\"check\">개인정보수집이용동의</label>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<a href=\"javascript:send_form();\" class=\"quick_btn\">상담 신청</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("  <!-- end 우측 문의 퀵배너 -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		function call_gugn(val){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\"\r\n");
      out.write("				,url:\"/html/dh/gugun2\"\r\n");
      out.write("				,data:{'ajax':1,'city':val}\r\n");
      out.write("				,error:function(xhr){console.log(xhr.responseText);}\r\n");
      out.write("				,success:function(data){\r\n");
      out.write("					if(data){\r\n");
      out.write("						$(\"#gugun\").html(data);\r\n");
      out.write("					}\r\n");
      out.write("					else{\r\n");
      out.write("						$(\"#gugun\").html('<option value=\"\">구/군</option>');\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		function send_form(){\r\n");
      out.write("			var quick_frm = document.quick_online;\r\n");
      out.write("			if(quick_frm.name.value==\"\"){\r\n");
      out.write("				alert('성함을 입력해주세요.');\r\n");
      out.write("				quick_frm.name.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}else if(quick_frm.data1.value==\"\"){\r\n");
      out.write("				alert('연락처를 입력해주세요.');\r\n");
      out.write("				quick_frm.data1.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}else if(quick_frm.email.value==\"\"){\r\n");
      out.write("				alert('이메일을 입력해주세요.');\r\n");
      out.write("				quick_frm.email.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			/*}else if(quick_frm.sido.value==\"\"){\r\n");
      out.write("				alert('도/시를 선택해주세요.');\r\n");
      out.write("				return;\r\n");
      out.write("			}else if(quick_frm.gugun.value==\"\"){\r\n");
      out.write("				alert('구/군을 선택해주세요.');\r\n");
      out.write("				quick_frm.gugun.focus();\r\n");
      out.write("				return;*/\r\n");
      out.write("			}else if($('#check').prop('checked')==false){\r\n");
      out.write("				alert('개인정보수집이용에 동의해주세요.');\r\n");
      out.write("				return;\r\n");
      out.write("			}else{\r\n");
      out.write("				quick_frm.submit();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 인스타그램 -->\r\n");
      out.write("	<div id=\"f_insta\">\r\n");
      out.write("		<p class=\"htit\">Follow us on instagram</p>\r\n");
      out.write("		<p class=\"id\"><span>@Metabuckscoffee</span></p>\r\n");
      out.write("\r\n");
      out.write("	</div><!-- END 인스타그램 -->\r\n");
      out.write("\r\n");
      out.write("	<!--Footer-->\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		업체명 : (주)메타벅스 | 대표자명 : TeamC | 사업자등록번호 : 123-45-67890 <br>\r\n");
      out.write("		주소 : 전주시 덕진구 금암1동 이젠컴퓨터아카데미 5층 | Tel : 010-1234-5678\r\n");
      out.write("		Copyright ⓒ 2022 (주)메타벅스. All Rights Reserved.\r\n");
      out.write("	</div><!--END Footer-->\r\n");
      out.write("\r\n");
      out.write(" </div><!--END Wrap-->\r\n");
      out.write("\r\n");
      out.write("<!-- ↓ 아래있는 /div 태그 두개는  joinok에 구문이 잘 안닫혀 있어서 추가한 것-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
