/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-27 03:08:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.METAORDER.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.vo.*;
import meta.dto.*;

public final class orderok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");


accountVO user = (accountVO)session.getAttribute("login");

if( user == null )
{
	response.getWriter().print("<script>alert('로그인 후 이용 바랍니다.'); location.href = 'index.jsp';</script>");
	return;
}

request.setCharacterEncoding("UTF-8");

String hname	= request.getParameter("hname");

//System.out.println("orderok jsp request parameta : hname = " + hname);

ListDTO list = new ListDTO();
menuDTO dto = new menuDTO();
productVO vo = dto.ProRead(hname);

//값이 없거나 다를때 
if( hname == null || hname.equals("")|| !hname.equals(hname))
{
	response.sendRedirect("index.jsp");
	return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("	<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>메타벅스</title>\r\n");
      out.write("		<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/all.css\">\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("		<script src=\"../js/common.js\"></script>		\r\n");
      out.write("		<script src=\"../js/cart.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	//이전값\r\n");
      out.write("	var oldObj = null;\r\n");
      out.write("	\r\n");
      out.write("	function select(obj)\r\n");
      out.write("	{\r\n");
      out.write("		//document.getElementById('sel').className = \"sel cup size\"\r\n");
      out.write("		//alert(\"test\");\r\n");
      out.write("		//alert($(obj).find(\"#sel\").attr(\"class\"));\r\n");
      out.write("		//$(obj).find(\"#sel\").removeClass(\"cup size\");\r\n");
      out.write("		\r\n");
      out.write("		if(oldObj == obj) return;\r\n");
      out.write("		\r\n");
      out.write("		//이 전에 선택이 되어있을 때\r\n");
      out.write("		if( oldObj != null)\r\n");
      out.write("		{\r\n");
      out.write("			//기존의 선택을 제거\r\n");
      out.write("			$(oldObj).find(\"#sel\").removeClass(\"sel cup size\");\r\n");
      out.write("			$(oldObj).find(\"#sel\").addClass(\"cup size\");\r\n");
      out.write("			$(\"#shot\").html(\"0\");\r\n");
      out.write("		}\r\n");
      out.write("		//클릭한 자식의 #sel 아이디에 클래스를 설정\r\n");
      out.write("		$(obj).find(\"#sel\").removeClass(\"cup size\");\r\n");
      out.write("		$(obj).find(\"#sel\").addClass(\"sel cup size\");\r\n");
      out.write("		\r\n");
      out.write("		var value = $(obj).find(\"#menu_price\").val();\r\n");
      out.write("		$(\"#basic_price\").val(value);\r\n");
      out.write("		$(\"#div_price\").html(value + \"원\");\r\n");
      out.write("		\r\n");
      out.write("		oldObj = obj;\r\n");
      out.write("\r\n");
      out.write("		var info = $(obj).find(\"#menu_item\").val();\r\n");
      out.write("		$(\"#select_item\").val(info);\r\n");
      out.write("		\r\n");
      out.write("		MakeSum();		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//옵션값을 보내기\r\n");
      out.write("	function Option()\r\n");
      out.write("	{\r\n");
      out.write("		var select_item = $(\"#select_item\").val();javascript:void(0);\r\n");
      out.write("		var basic_price = $(\"#basic_price\").val();javascript:void(0);\r\n");
      out.write("		basic_price = parseInt(basic_price);\r\n");
      out.write("		if(basic_price == 0)\r\n");
      out.write("		{\r\n");
      out.write("			alert(\"제품을 선택하여 주세요.\");\r\n");
      out.write("			return;	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var datalist = \"\";\r\n");
      out.write("		\r\n");
      out.write("		$(\"#shot\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var shot	= document.getElementById(\"shot\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += shot;				\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		$(\"#syrup\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var syrup	= document.getElementById(\"syrup\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += syrup;				\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		$(\"#count\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var count	= document.getElementById(\"count\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += count;			\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		\r\n");
      out.write("		$(\"#sel_option\").val(datalist);\r\n");
      out.write("		document.option.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//옵션값을 보내기\r\n");
      out.write("	function putItemIntoCart()\r\n");
      out.write("	{\r\n");
      out.write("		var select_item = $(\"#select_item\").val();javascript:void(0);\r\n");
      out.write("		var basic_price = $(\"#basic_price\").val();javascript:void(0);\r\n");
      out.write("		basic_price = parseInt(basic_price);\r\n");
      out.write("		if(basic_price == 0)\r\n");
      out.write("		{\r\n");
      out.write("			alert(\"제품을 선택하여 주세요.\");\r\n");
      out.write("			return;	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var datalist = \"\";\r\n");
      out.write("		\r\n");
      out.write("		$(\"#shot\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var shot	= document.getElementById(\"shot\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += shot;				\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		$(\"#syrup\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var syrup	= document.getElementById(\"syrup\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += syrup;				\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		$(\"#count\").each(\r\n");
      out.write("			function()\r\n");
      out.write("			{\r\n");
      out.write("				var count	= document.getElementById(\"count\").innerHTML;\r\n");
      out.write("				if(datalist != \"\") datalist += \",\";\r\n");
      out.write("				datalist += count;			\r\n");
      out.write("			}\r\n");
      out.write("		);\r\n");
      out.write("		\r\n");
      out.write("		$(\"#sel_option\").val(datalist);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url: \"cart.jsp\",\r\n");
      out.write("			dataType: \"html\",\r\n");
      out.write("			data: \r\n");
      out.write("			{\r\n");
      out.write("				sel_option:$(\"#sel_option\").val(),\r\n");
      out.write("				select_item:$(\"#select_item\").val(),\r\n");
      out.write("				total_price:$(\"#total_price\").val()\r\n");
      out.write("		    },	\r\n");
      out.write("			success : function(data) \r\n");
      out.write("			{\r\n");
      out.write("				data = data.trim();\r\n");
      out.write("				window.location.href = \"../other/shopping.jsp\";\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//수량 증가감소\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$('#minus1').click(function(){\r\n");
      out.write("			SetItem(this,\"-\",1);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#plus1').click(function(){\r\n");
      out.write("			SetItem(this,\"+\",5);\r\n");
      out.write("		});\r\n");
      out.write("		$('#minus2').click(function(){\r\n");
      out.write("			SetItem(this,\"-\",0);			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#plus2').click(function(){\r\n");
      out.write("			SetItem(this,\"+\",5);\r\n");
      out.write("		});\r\n");
      out.write("		$('#minus3').click(function(){\r\n");
      out.write("			SetItem(this,\"-\",1);			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#plus3').click(function(){\r\n");
      out.write("			SetItem(this,\"+\",10);\r\n");
      out.write("		});\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("	//pID : 객체 ID\r\n");
      out.write("	//pMode : + 또는 -\r\n");
      out.write("	function SetItem(obj,pMode,pMax)\r\n");
      out.write("	{\r\n");
      out.write("		var subObj = null;\r\n");
      out.write("		var num  = 0;\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var basic_price = $(\"#basic_price\").val();\r\n");
      out.write("		basic_price = parseInt(basic_price);\r\n");
      out.write("		if(basic_price == 0)\r\n");
      out.write("		{\r\n");
      out.write("			alert(\"제품을 선택하여 주세요.\");\r\n");
      out.write("			return;	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( pMode == \"+\" )\r\n");
      out.write("		{\r\n");
      out.write("			subObj = $(obj).prev();\r\n");
      out.write("			stat = $(subObj).text();\r\n");
      out.write("			num = parseInt(stat,10);			\r\n");
      out.write("			num++;\r\n");
      out.write("			if( num > pMax )\r\n");
      out.write("			{\r\n");
      out.write("				//alert(\"더 이상 늘일 수 없습니다.\");\r\n");
      out.write("				num = pMax;\r\n");
      out.write("			}\r\n");
      out.write("		}else if( pMode == \"-\")\r\n");
      out.write("		{\r\n");
      out.write("			subObj = $(obj).next();\r\n");
      out.write("			stat = $(subObj).text();\r\n");
      out.write("			num = parseInt(stat,10);			\r\n");
      out.write("			num--;\r\n");
      out.write("			if( num < pMax )\r\n");
      out.write("			{\r\n");
      out.write("				//alert(\"더 이상 줄일 수 없습니다.\");\r\n");
      out.write("				num = pMax;\r\n");
      out.write("			}			\r\n");
      out.write("		}\r\n");
      out.write("		$(subObj).text(num);\r\n");
      out.write("		\r\n");
      out.write("		MakeSum();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//주문 총액을 계산한다.\r\n");
      out.write("	function MakeSum()\r\n");
      out.write("	{\r\n");
      out.write("		/*\r\n");
      out.write("		var basic_price = $(\"#basic_price\").val();\r\n");
      out.write("		basic_price = parseInt(basic_price);\r\n");
      out.write("		if(basic_price == 0)\r\n");
      out.write("		{\r\n");
      out.write("			return;	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//합계 금액을 계산한다.\r\n");
      out.write("		var count = $(\"#count\").text();\r\n");
      out.write("		count = parseInt(count);\r\n");
      out.write("		var sum_price = 0;\r\n");
      out.write("		sum_price = count * basic_price;\r\n");
      out.write("		$(\"#div_price\").html(\"결제금액: \" + comma(sum_price) + \"원\");\r\n");
      out.write("		*/\r\n");
      out.write("		\r\n");
      out.write("		//가격 계산하기 (샷*500 + 단품가격)*수량\r\n");
      out.write("		//var iPrice = (opt1 * 500 + sPrice) * opt3 ;\r\n");
      out.write("		\r\n");
      out.write("		//setText(\"div_price\",\"결제금액: \" + comma(getIntVal(\"basic_price\") * getIntText(\"count\") + (getIntText(\"shot\") * 500)) + \"원\");\r\n");
      out.write("		setText(\"div_price\",\"결제금액: \" + comma(((getIntText(\"shot\") * 500)+getIntVal(\"basic_price\"))*getIntText(\"count\")) + \"원\");\r\n");
      out.write("		setVal(\"total_price\", comma(((getIntText(\"shot\") * 500)+getIntVal(\"basic_price\"))*getIntText(\"count\")));\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("		<div id=\"strURL\"></div>\r\n");
      out.write("		<form id=\"option\" name=\"option\" method=\"get\" action=\"payment.jsp\">\r\n");
      out.write("		<table border=\"0\" align=center width=500px>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("					<a href=\"view.jsp\"><img src=\"../img/back.png\"></a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"height:100px;\">\r\n");
      out.write("				<td colspan=\"4\">\r\n");
      out.write("					<h2>\r\n");
      out.write("						");
      out.print( vo.getHname() );
      out.write("\r\n");
      out.write("					</h2>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"height:80px; \">\r\n");
      out.write("					<h3>사이즈</h3>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr align=\"center\">\r\n");
      out.write("						\r\n");
      out.write("			");

				int total = list.GetProTotal(hname); 
				//System.out.println(total);
				list.GetproList(hname);
				for(int i=0; i < list.GetProTotal(hname); i++)
				{
					vo = list.GetMenu(i);
				
      out.write("\r\n");
      out.write("				<td>\r\n");
      out.write("					<a href=\"javascript:void(0);\" onclick=\"select(this);\">\r\n");
      out.write("						<div id=\"sel\" class=\"cup size\" style=\"font-size:14px;\" >");
      out.print( vo.getDiv_name() );
      out.write("\r\n");
      out.write("							");

							String info = vo.getDiv_name() + "@" + hname + "@" + vo.getPro_price() + "@" + vo.getPro_no();
							
      out.write("\r\n");
      out.write("							<input type=\"hidden\" id=\"menu_item\" name=\"menu_item\" value=\"");
      out.print( info );
      out.write("\" >\r\n");
      out.write("							<input type=\"hidden\" id=\"select_item\" name=\"select_item\" value=\"\" >\r\n");
      out.write("							<input type=\"hidden\" id=\"menu_price\" name=\"menu_price\" value=\"");
      out.print( vo.getPro_price() );
      out.write("\" >\r\n");
      out.write("							<input type=\"hidden\" id=\"sel_option\" name=\"sel_option\" value=\"\" >\r\n");
      out.write("							<div>\r\n");
      out.write("								<img src=\"../img/size.png\"></div><div style=\"font-size:12px;\">");
      out.print(vo.getVolume() );
      out.print( vo.getUnit() );
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</td>\r\n");
      out.write("				");

			}
			
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"height:80px; \">\r\n");
      out.write("					<h3>옵션</h3>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\" height:80px\">\r\n");
      out.write("					<h3>샷</h3>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td colspan=\"3\" align=\"right\">\r\n");
      out.write("					<input style=\"width:30px; height:30px; font-size:20px; \" id=\"minus1\" type=\"button\" value=\"-\">\r\n");
      out.write("					 <span id=\"shot\" >0</span> \r\n");
      out.write("					<input style=\"width:30px; height:30px; font-size:20px; \" id=\"plus1\" type=\"button\" value=\"+\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\" height:80px\">\r\n");
      out.write("					<h3>시럽</h3>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td colspan=\"3\" align=\"right\">\r\n");
      out.write("					<input style=\"width:30px; height:30px; font-size:20px; \" id=\"minus2\" type=\"button\" value=\"-\">\r\n");
      out.write("					 <span id=\"syrup\">0</span> \r\n");
      out.write("					<input style=\"width:30px; height:30px; font-size:20px; \" id=\"plus2\" type=\"button\" value=\"+\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr style=\"overflow: hidden;position: fixed;\r\n");
      out.write("						background-color: white; /*임의색상*/\r\n");
      out.write("						bottom: 0;\r\n");
      out.write("						height: 12rem;\">\r\n");
      out.write("							<td width=117px align=center>\r\n");
      out.write("								<input style=\"width:30px; height:30px; font-size:20px; \" id=\"minus3\" type=\"button\" value=\"-\">\r\n");
      out.write("								 <span id=\"count\" >1</span> \r\n");
      out.write("								<input style=\"width:30px; height:30px; font-size:20px; \" id=\"plus3\" type=\"button\" value=\"+\">\r\n");
      out.write("							</td>\r\n");
      out.write("							<td width=300px align=center>\r\n");
      out.write("								<input type=\"hidden\" id=\"basic_price\" name=\"basic_price\" value=\"0\">\r\n");
      out.write("								<input type=\"hidden\" id=\"total_price\" name=\"total_price\" value=\"0\">\r\n");
      out.write("								<div id=\"div_price\">제품을 선택하세요.</div>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			<tr style=\"position: fixed;\r\n");
      out.write("						background-color: white; /*임의색상*/\r\n");
      out.write("						bottom: 0;\r\n");
      out.write("						height: 6rem;\">\r\n");
      out.write("				<td style=\"width:150px;\"align=center>\r\n");
      out.write("					<a href=\"#\"><img src=\"../img/unlike.png\"></a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td align=center>\r\n");
      out.write("					<a class=\"btn re\" href=\"javascript:putItemIntoCart();\">담기</a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td align=center><!-- payment.jsp?name=");
      out.print( vo.getDiv_name() );
      out.write("&hname=");
      out.print( hname );
      out.write(" -->\r\n");
      out.write("					<a class=\"btn\" href=\"javascript:Option();\">주문하기</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"cartbody\"></div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
