/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-27 05:30:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HOME.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.dto.*;
import meta.vo.*;

public final class userinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/HOME/mypage/../include/head3.jsp", Long.valueOf(1653628156243L));
    _jspx_dependants.put("/HOME/mypage/../include/tail.jsp", Long.valueOf(1653310125863L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//String userid  = (String) session.getAttribute("id");
//로그인 정보를 얻는다.
String userid="";
accountVO loginVO = (accountVO)session.getAttribute("accountVO");




if(loginVO !=null)
{
 userid = loginVO.id();
}

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <title>MetaBucks</title>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=1180\">\r\n");
      out.write("	<meta name=\"Author\" content=\"MetaBucks\">\r\n");
      out.write("	<meta name=\"description\" content=\"메타벅스\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//fonts.googleapis.com/earlyaccess/notosanskr.css\" />\r\n");
      out.write("	<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/@default.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/slick.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/common.js\"></script>\r\n");
      out.write("	<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write("	\r\n");
      out.write(" <!--Wrap-->\r\n");
      out.write(" <div id=\"wrap\" class=\"\">\r\n");
      out.write("	<!--Header-->\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"h_inner\" style=\"padding-bottom: 0px;\">\r\n");
      out.write("			<span class=\"gnb_bg\"></span>\r\n");
      out.write("			<div class=\"join\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"../login/login.jsp\">\r\n");
      out.write("						");

						if(loginVO == null)
						{
							
      out.write("\r\n");
      out.write("								Sign In\r\n");
      out.write("							");

						}else
						{
							
      out.write("\r\n");
      out.write("							( ");
      out.print( userid );
      out.write(" )님 환영합니다\r\n");
      out.write("							\r\n");
      out.write("							<a href=\"../login/logout.jsp\" class=\"btnlogout\">로그아웃</a>\r\n");
      out.write("							");

						}	
					
      out.write("</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<h1 id=\"logo\"><a href=\"../index.jsp\"><span></span>메타벅스</a></h1>\r\n");
      out.write("			<div class=\"gnb_wrap\" id=\"gnb_wrap\">\r\n");
      out.write("				<ul class=\"gnb\">\r\n");
      out.write("					<li><a href=\"../nav/about1.jsp\">About us</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../nav/about1.jsp\">Brand</a></li>\r\n");
      out.write("							<li><a href=\"../nav/about2.jsp\">Coffee</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"../nav/menu.jsp\">MENU</a></li>\r\n");
      out.write("					<li><a href=\"../nav/store.jsp\">SHOP</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../nav/store.jsp\">매장위치안내</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"../nav/contact.jsp\">Contact</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../board/bindex.jsp\">공지사항</a></li>\r\n");
      out.write("							<li><a href=\"../nav/contact.jsp\">이메일 문의하기</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					");
 
					if(loginVO != null)
					{
						
      out.write("\r\n");
      out.write("						<li><a href=\"../mypage/userinfo.jsp\">Members</a>\r\n");
      out.write("							<ul class=\"gsnb\">\r\n");
      out.write("								<li><a href=\"../mypage/userinfo.jsp\">My Page</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("						\r\n");
      out.write("						<script>\r\n");
      out.write("						//alert(\" 로그인 해주세요\");\r\n");
      out.write("						</script>\r\n");
      out.write("						");

					}
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div><!--END Header-->\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');




accountVO vo = new accountVO();
accountDTO dto = new accountDTO();





if(loginVO !=null)
{
 userid = loginVO.id();
 String email =loginVO.em();
 loginVO.pw();
 loginVO.hp();
 
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Container-->\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"sv_wrap K01\">\r\n");
      out.write("			<p class=\"sv_tit\"><img src=\"../image/tit_K05.png\" alt=\"MENU\"></p>\r\n");
      out.write("			<p class=\"page_path\"><a href=\"/\">HOME</a><span class=\"arr\"></span> Members<span class=\"arr\"></span>마이페이지</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Content-->\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h2 class=\"page_tit\">마이페이지</h2>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"outer tint\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<h3 class=\"hidden\">마이페이지</h3>\r\n");
      out.write("\r\n");
      out.write("					<!--마이페이지 -->\r\n");
      out.write("					<div class=\"myp\">\r\n");
      out.write("						<P align=\"center\">[");
      out.print( userid  );
      out.write("]님의 회원정보 입니다.</P>\r\n");
      out.write("					</div>\r\n");
      out.write("						<!--<div>	\r\n");
      out.write("							<ul class=\"myp\">\r\n");
      out.write("								<li><a href=\"order.jsp\">주문내역</a></li>\r\n");
      out.write("								<li><a href=\"mymenuok.jsp\">나의 메뉴</a></li>\r\n");
      out.write("								<li><a href=\"money.jsp\">나의 적립금<span style=\"color:blue;\">400원</span></a></li>\r\n");
      out.write("								<li><a href=\"charge.jsp\">예치금<span style=\"color:blue;\">50000원</span></a></li>\r\n");
      out.write("								<li><a href=\"pay.jsp\">결제수단 관리</a></li>\r\n");
      out.write("								<li><a href=\"userinfo.jsp\">나의 정보</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							\r\n");
      out.write("						</div>  -->\r\n");
      out.write("						<h1 class=\"myps\"></h1>\r\n");
      out.write("						<table class=\"boardhan\"  border=\"1\" style=\"width:600px;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:150px; height:20px;\" >닉네임</td>\r\n");
      out.write("								<td style=\"width:150px;\">");
      out.print(loginVO.nickname() );
      out.write("</td>\r\n");
      out.write("								<td class=myinfos style=\"width:80px; height:20px;\">이메일</td>\r\n");
      out.write("								<td style=\"width:100px;\">");
      out.print(loginVO.em() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:150px; height:20px;\" >아이디</td>\r\n");
      out.write("								<td style=\"width:150px;\">");
      out.print(loginVO.id() );
      out.write("</td>\r\n");
      out.write("								<td class=myinfos style=\"width:80px; height:20px;\">휴대전화</td>\r\n");
      out.write("								<td style=\"width:100px;\">");
      out.print(loginVO.hp() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">성별</td>\r\n");
      out.write("								<td style=\"width:100px;\">\r\n");
      out.write("									<input type=\"radio\" name=\"gender\" value=\"man\" ");
      out.print( loginVO.gen().equals("1") ? "checked" : "" );
      out.write(" >남\r\n");
      out.write("									<input type=\"radio\" name=\"gender\" value=\"woman\" ");
      out.print( loginVO.gen().equals("0") ? "checked" : "" );
      out.write(">여</td>\r\n");
      out.write("								<td class=myinfos style=\"width:80px;\">생년월일</td>\r\n");
      out.write("								<td style=\"width:100px;\">");
      out.print(loginVO.age() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("							<h1 class=\"myps\"></h1>\r\n");
      out.write("						<p align=\"center\">고객님이 선호하는 메뉴</p>\r\n");
      out.write("						<table  class=\"boardhan\" border=\"1\" style=\"width:70%;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >이미지</td>\r\n");
      out.write("								<td style=\"width:100px;\">메뉴명 </td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\">금액</td>\r\n");
      out.write("								<td style=\"width:30px; text-align:center;\">선택\r\n");
      out.write("								<input type=\"checkbox\" id=\"ckall\" name=\"ckall\"></td>\r\n");
      out.write("								\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\"><span class=\"img-w50\"><img src=\"https://silverwoods.synology.me:8081/productimage/americano222.png\" alt=\"\"></span></td>\r\n");
      out.write("								<td style=\"width:100px;\">아메리카노</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">1500원</td>\r\n");
      out.write("								<td style=\"text-align:center;\">\r\n");
      out.write("					\r\n");
      out.write("								<input type=\"checkbox\" name=\"chkno\" value=\"\">\r\n");
      out.write("					\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							  \r\n");
      out.write("						</table>\r\n");
      out.write("						<h1 class=\"myps\"></h1>\r\n");
      out.write("						\r\n");
      out.write("						<P align=\"center\">[");
      out.print( userid  );
      out.write("]님의 주문내역 입니다.</P>\r\n");
      out.write("						<table class=\"boardhan\" border=\"1\" style=\"width:700px;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >주문일자</td>\r\n");
      out.write("								<td style=\"width:100px;\">내용 </td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\">금액</td>\r\n");
      out.write("								<td style=\"width:30px;\">결제수단 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-01-02 15:26:30</td>\r\n");
      out.write("								<td style=\"width:100px;\">아메리카노Ice</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">1500원</td>\r\n");
      out.write("								<td style=\"width:30px;\">신용카드 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-03-05 14:47:05 </td>\r\n");
      out.write("								<td style=\"width:100px;\">카페라테Ice</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2000원</td>\r\n");
      out.write("								<td style=\"width:30px;\">신용카드 </td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<h1 class=\"myps\"></h1>\r\n");
      out.write("						\r\n");
      out.write("						<P align=\"center\">[");
      out.print( userid  );
      out.write("]님의 사용가능한 적립금액은 총 <span style=\"color:blue;\">");
      out.print(loginVO.point() );
      out.write("원</span>입니다.</P>\r\n");
      out.write("						<p align=\"center\">적립내역</p>\r\n");
      out.write("						<table class=\"boardhan\"  border=\"1\" style=\"width:600px;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >거래일자</td>\r\n");
      out.write("								<td style=\"width:100px;\">주문번호</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\">내용</td>\r\n");
      out.write("								<td style=\"width:100px;\">적립금</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-01-02</td>\r\n");
      out.write("								<td style=\"width:100px;\"></td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">첫가입적립금</td>\r\n");
      out.write("								<td style=\"width:100px;\">200원</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-03-05 </td>\r\n");
      out.write("								<td style=\"width:100px;\">P15234</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\">제품구매적립</td>\r\n");
      out.write("								<td style=\"width:70px;\">200원</td>\r\n");
      out.write("								\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<h1 class=\"myps\"></h1>\r\n");
      out.write("						<P align=\"center\">[");
      out.print( userid  );
      out.write("]님의 사용가능한 예치금액은 총 <span style=\"color:blue;\">");
      out.print(loginVO.deposit() );
      out.write("원</span>입니다.</P>\r\n");
      out.write("						<p align=\"center\">예치금 충전내역</p>\r\n");
      out.write("						<table class=\"boardhan\"  border=\"1\" style=\"width:70%;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >충전일자</td>\r\n");
      out.write("								<td style=\"width:100px;\">내용 </td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\">금액</td>\r\n");
      out.write("								\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-01-02 15:26:30</td>\r\n");
      out.write("								<td style=\"width:100px;\">신용카드</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">50000원</td>\r\n");
      out.write("							\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">2022-03-05 14:47:05 </td>\r\n");
      out.write("								<td style=\"width:100px;\">계좌 이체</td>\r\n");
      out.write("								<td class=myinfos style=\"width:70px;\">10000원</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<h1 class=\"myps\"></h1>\r\n");
      out.write("						<p align=\"center\">결제수단 관리</p>\r\n");
      out.write("						<table class=\"boardhan\"border=\"1\" style=\"width:800px;\" class=\"myinfo\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >결제방식</td>\r\n");
      out.write("								<td>\r\n");
      out.write("				                    <input type=\"radio\" name=\"pay\" value=\"credit\" ");
      out.print( loginVO.pay_str().equals("신용카드") ? "checked" : "" );
      out.write(">신용/체크카드\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<div class=\"\"><a href=\"card.jsp\" class=\"btnCommon\">카드등록</a></div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >결제방식</td>\r\n");
      out.write("								<td><input type=\"radio\" name=\"pay\" value=\"cash\" ");
      out.print( loginVO.pay_str().equals("예치금") ? "checked" : "" );
      out.write(">예치금</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<div class=\"\"><a href=\"deposit.jsp\" class=\"btnCommon\">예치금충전</a></div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=myinfos style=\"width:70px; height:20px;\" >결제방식</td>\r\n");
      out.write("								<td><input type=\"radio\" name=\"pay\" value=\"cash\" ");
      out.print( loginVO.pay_str().equals("적립금") ? "checked" : "" );
      out.write(">적립금</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<div class=\"\"><a href=\"money.jsp\" class=\"btnCommon\">적립금보기</a></div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<div class=\"btnCommon type2\">\r\n");
      out.write("							<a href=\"infomody.jsp\" class=\"btnBlack\">정보 수정</a>\r\n");
      out.write("							<a href=\"../index.jsp\" class=\"btnGray\">메인으로</a>\r\n");
      out.write("						</div>	\r\n");
      out.write("					</div><!-- END Inner -->\r\n");
      out.write("			</div><!-- END Outer -->\r\n");
      out.write("		</div><!-- END Content -->\r\n");
      out.write("	</div><!--END Container-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 인스타그램 -->\r\n");
      out.write("	<div id=\"f_insta\">\r\n");
      out.write("		<p class=\"htit\">Follow us on instagram</p>\r\n");
      out.write("		<p class=\"id\"><span>@Metabuckscoffee</span></p>\r\n");
      out.write("\r\n");
      out.write("	</div><!-- END 인스타그램 -->\r\n");
      out.write("\r\n");
      out.write("	<!--Footer-->\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		업체명 : (주)메타벅스 | 대표자명 : TeamC | 사업자등록번호 : 123-45-67890 <br>\r\n");
      out.write("		주소 : 전주시 덕진구 금암1동 이젠컴퓨터아카데미 5층 | Tel : 010-1234-5678\r\n");
      out.write("		Copyright ⓒ 2022 (주)메타벅스. All Rights Reserved.\r\n");
      out.write("	</div><!--END Footer-->\r\n");
      out.write("\r\n");
      out.write(" </div><!--END Wrap-->\r\n");
      out.write("\r\n");
      out.write("<!-- ↓ 아래있는 /div 태그 두개는  joinok에 구문이 잘 안닫혀 있어서 추가한 것-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
