/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-27 06:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HOME.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import meta.vo.*;
import meta.dto.*;
import meta.util.*;
import meta.util.*;
import meta.vo.*;
import meta.dto.*;
import meta.vo.*;

public final class bindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/HOME/board/../include/head3.jsp", Long.valueOf(1653628156243L));
    _jspx_dependants.put("/HOME/board/../include/tail.jsp", Long.valueOf(1653310125863L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("meta.vo");
    _jspx_imports_packages.add("meta.dto");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("meta.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");


SearchVO searchVO = new SearchVO(request);//생성자에 REQUEST값 넘겨주면  search VO에서 받음
ListDTO  listDTO  = new ListDTO(searchVO);//검색조건을 listDTO에 넘겨줌
Paging   paging   = new Paging(searchVO);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//String userid  = (String) session.getAttribute("id");
//로그인 정보를 얻는다.
String userid="";
accountVO loginVO = (accountVO)session.getAttribute("accountVO");




if(loginVO !=null)
{
 userid = loginVO.id();
}

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <title>MetaBucks</title>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=1180\">\r\n");
      out.write("	<meta name=\"Author\" content=\"MetaBucks\">\r\n");
      out.write("	<meta name=\"description\" content=\"메타벅스\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//fonts.googleapis.com/earlyaccess/notosanskr.css\" />\r\n");
      out.write("	<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/@default.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/slick.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/common.js\"></script>\r\n");
      out.write("	<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write("	\r\n");
      out.write(" <!--Wrap-->\r\n");
      out.write(" <div id=\"wrap\" class=\"\">\r\n");
      out.write("	<!--Header-->\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"h_inner\" style=\"padding-bottom: 0px;\">\r\n");
      out.write("			<span class=\"gnb_bg\"></span>\r\n");
      out.write("			<div class=\"join\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"../login/login.jsp\">\r\n");
      out.write("						");

						if(loginVO == null)
						{
							
      out.write("\r\n");
      out.write("								Sign In\r\n");
      out.write("							");

						}else
						{
							
      out.write("\r\n");
      out.write("							( ");
      out.print( userid );
      out.write(" )님 환영합니다\r\n");
      out.write("							\r\n");
      out.write("							<a href=\"../login/logout.jsp\" class=\"btnlogout\">로그아웃</a>\r\n");
      out.write("							");

						}	
					
      out.write("</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<h1 id=\"logo\"><a href=\"../index.jsp\"><span></span>메타벅스</a></h1>\r\n");
      out.write("			<div class=\"gnb_wrap\" id=\"gnb_wrap\">\r\n");
      out.write("				<ul class=\"gnb\">\r\n");
      out.write("					<li><a href=\"../nav/about1.jsp\">About us</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../nav/about1.jsp\">Brand</a></li>\r\n");
      out.write("							<li><a href=\"../nav/about2.jsp\">Coffee</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"../nav/menu.jsp\">MENU</a></li>\r\n");
      out.write("					<li><a href=\"../nav/store.jsp\">SHOP</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../nav/store.jsp\">매장위치안내</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"../nav/contact.jsp\">Contact</a>\r\n");
      out.write("						<ul class=\"gsnb\">\r\n");
      out.write("							<li><a href=\"../board/bindex.jsp\">공지사항</a></li>\r\n");
      out.write("							<li><a href=\"../nav/contact.jsp\">이메일 문의하기</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					");
 
					if(loginVO != null)
					{
						
      out.write("\r\n");
      out.write("						<li><a href=\"../mypage/userinfo.jsp\">Members</a>\r\n");
      out.write("							<ul class=\"gsnb\">\r\n");
      out.write("								<li><a href=\"../mypage/userinfo.jsp\">My Page</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("						\r\n");
      out.write("						<script>\r\n");
      out.write("						//alert(\" 로그인 해주세요\");\r\n");
      out.write("						</script>\r\n");
      out.write("						");

					}
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div><!--END Header-->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!--Container-->\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"sv_wrap K01\">\r\n");
      out.write("			<p class=\"sv_tit\"><img src=\"../image/tit_K04.png\" alt=\"contact\"></p>\r\n");
      out.write("			<p class=\"page_path\"><a href=\"../index.jsp\">HOME</a><span class=\"arr\"></span> Contact<span class=\"arr\"></span>공지사항</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Content-->\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<h2 class=\"page_tit\">공지사항</h2>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"outer tint\">\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<h3 class=\"hidden\">공지사항</h3>\r\n");
      out.write("\r\n");
      out.write("					<!-- 검색 테이블 -->\r\n");
      out.write("					<table align=\"center\" border=\"0\" style=\"width:100%\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td align=\"center\">\r\n");
      out.write("								<form id=\"search\" name=\"search\" method=\"get\" action=\"bindex.jsp\">\r\n");
      out.write("									<select name=\"search_kind\" onchange=\"document.search.submit();\">\r\n");
      out.write("										<option value=\"\"   ");
      out.print( searchVO.getKind().equals("") ? "selected" : "" );
      out.write(">전체</option>\r\n");
      out.write("										<option value=\"01\" ");
      out.print( searchVO.getKind().equals("01") ? "selected" : "" );
      out.write(">공지사항</option>\r\n");
      out.write("										<option value=\"02\" ");
      out.print( searchVO.getKind().equals("02") ? "selected" : "" );
      out.write(">이벤트</option>\r\n");
      out.write("										<option value=\"03\" ");
      out.print( searchVO.getKind().equals("03") ? "selected" : "" );
      out.write(">설문조사</option>\r\n");
      out.write("\r\n");
      out.write("									</select>\r\n");
      out.write("									<select name=\"search_type\">\r\n");
      out.write("										<option value=\"T\" ");
      out.print( searchVO.getType().equals("T") ? "selected" : "" );
      out.write(">제목</option>\r\n");
      out.write("										<option value=\"C\" ");
      out.print( searchVO.getType().equals("C") ? "selected" : "" );
      out.write(">내용</option>\r\n");
      out.write("										<option value=\"A\" ");
      out.print( searchVO.getType().equals("A") ? "selected" : "" );
      out.write(">제목 + 내용</option>\r\n");
      out.write("									</select>\r\n");
      out.write("									<input type=\"text\" size=\"10\" id=\"search_key\" name=\"search_key\" value=\"");
      out.print( searchVO.getKeyword() );
      out.write("\">\r\n");
      out.write("									<a href=\"javascript:document.search.submit();\"><img src=\"../image/search.png\" height=\"15px\"></a>\r\n");
      out.write("								</form>\r\n");
      out.write("							</td>\r\n");
      out.write("\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("					<!-- test 테이블 -->\r\n");
      out.write("					<!-- 일반 게시판 리스트 -->\r\n");
      out.write("					<table class=\"board-list\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"col-num\">No.</th>\r\n");
      out.write("								<th>제목</th>\r\n");
      out.write("								<th class=\"col-writer\">작성자</th>\r\n");
      out.write("								<th class=\"col-date\">날짜</th>\r\n");
      out.write("								<th class=\"col-re\">조회</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

								//게시물의 갯수를 얻는다.
								int total = listDTO.GetTotal();
	
								listDTO.GetList(searchVO.getCurpage());//arraylist에 게시물 넣음
	
								int size = listDTO.GetListTotal();
								int seqno = total - (searchVO.getCurpage() - 1) * 10;
								for(int i=0; i < size; i++)
								{
									boardVO vo = listDTO.GetItem(i);
									
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>");
      out.print( seqno-- );
      out.write("</td>\r\n");
      out.write("								<td class=\"list-tit\"><a href=\"view.jsp?");
      out.print( searchVO.GetViewLink(vo.getBoard_no(),vo.getBoard_kind()) );
      out.write('"');
      out.write('>');
      out.print( vo.getBoard_title() );
      out.write("</a></td>\r\n");
      out.write("								<td>관리자</td>\r\n");
      out.write("								<td>");
      out.print(vo.getBoard_date() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print(vo.getBoard_hit() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("								");

									}
									if(total == 0)
									{
										
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td colspan=\"5\" style=\"background-color:#f4f4f4;height:80px;text-align:center;\">\r\n");
      out.write("												조회된 자료가 없습니다.\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										");

									}
									
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table><!-- END 일반 게시판 리스트 -->\r\n");
      out.write("					<div class=\"board-pager\">\r\n");
      out.write("						<div class=\"paginate\">\r\n");
      out.write("							");

							paging.setTotal(total, searchVO.getCurpage());

							if(paging.getStartBlock() != 1)//시작블럭이 1이 아니면
							{
								
      out.write("\r\n");
      out.write("								<a href=\"bindex.jsp?");
      out.print( searchVO.GetPageLink(paging.getStartBlock() - 1) );
      out.write("\">이전 블럭</a> |\r\n");
      out.write("								");

							}

							for(int pageno = paging.getStartBlock(); pageno <= paging.getEndBlock(); pageno++)
							{
								if(searchVO.getCurpage() == pageno)
								{
									
      out.write("<a href=\"bindex.jsp?");
      out.print( searchVO.GetPageLink(pageno) );
      out.write("\"><span style= \"font-weight: bold; text-align:center;\">");
      out.print( pageno );
      out.write("</span></a>  \r\n");
      out.write("									");

								}else
								{
									
      out.write("<a href=\"bindex.jsp?");
      out.print( searchVO.GetPageLink(pageno) );
      out.write('"');
      out.write('>');
      out.print( pageno );
      out.write("</a> \r\n");
      out.write("									");

								}
							}

							if(paging.getEndBlock() != paging.getMaxpage())//전체 페이지가 아니면
							{
								
      out.write("\r\n");
      out.write("								<a href=\"bindex.jsp?");
      out.print( searchVO.GetPageLink(paging.getEndBlock() + 1) );
      out.write("\">다음 블럭</a>\r\n");
      out.write("								");

							}
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("						<table align=\"center\" border=\"0\" style=\"width:70%;\" >\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td  Style=\"text-align:right\">\r\n");
      out.write("								");

								if(userid == null)
								{
									
      out.write("<a href=\"javascript:alert('로그인 해야 글쓰기가 가능합니다.');\" class=\"btnlogout\">글쓰기</a>");

								}else
								{
									
      out.write("<a  href=\"../board/write.jsp?");
      out.print( searchVO.GetPageLink(searchVO.getCurpage()) );
      out.write("\" class=\"btn-normal-s\">글쓰기</a>");

								}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td style=\"text-align:center\">\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div><!-- END Inner -->\r\n");
      out.write("			</div><!-- END Outer -->\r\n");
      out.write("		</div><!-- END Content -->\r\n");
      out.write("	</div><!--END Container-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 인스타그램 -->\r\n");
      out.write("	<div id=\"f_insta\">\r\n");
      out.write("		<p class=\"htit\">Follow us on instagram</p>\r\n");
      out.write("		<p class=\"id\"><span>@Metabuckscoffee</span></p>\r\n");
      out.write("\r\n");
      out.write("	</div><!-- END 인스타그램 -->\r\n");
      out.write("\r\n");
      out.write("	<!--Footer-->\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		업체명 : (주)메타벅스 | 대표자명 : TeamC | 사업자등록번호 : 123-45-67890 <br>\r\n");
      out.write("		주소 : 전주시 덕진구 금암1동 이젠컴퓨터아카데미 5층 | Tel : 010-1234-5678\r\n");
      out.write("		Copyright ⓒ 2022 (주)메타벅스. All Rights Reserved.\r\n");
      out.write("	</div><!--END Footer-->\r\n");
      out.write("\r\n");
      out.write(" </div><!--END Wrap-->\r\n");
      out.write("\r\n");
      out.write("<!-- ↓ 아래있는 /div 태그 두개는  joinok에 구문이 잘 안닫혀 있어서 추가한 것-->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
